allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@tarojs/api@4.3.0'
  - '@tarojs/binding-darwin-arm64@4.3.0'
  - '@tarojs/binding-darwin-x64@4.3.0'
  - '@tarojs/binding-linux-arm64-gnu@4.3.0'
  - '@tarojs/binding-linux-x64-gnu@4.3.0'
  - '@tarojs/binding-win32-x64-msvc@4.3.0'
  - '@tarojs/binding@4.3.0'
  - '@tarojs/cli@4.3.0'
  - '@tarojs/components-react@4.3.0'
  - '@tarojs/components@4.3.0'
  - '@tarojs/helper@4.3.0'
  - '@tarojs/plugin-framework-react@4.3.0'
  - '@tarojs/plugin-generator@4.3.0'
  - '@tarojs/plugin-platform-h5@4.3.0'
  - '@tarojs/plugin-platform-weapp@4.3.0'
  - '@tarojs/react@4.3.0'
  - '@tarojs/router@4.3.0'
  - '@tarojs/runner-utils@4.3.0'
  - '@tarojs/runtime@4.3.0'
  - '@tarojs/service@4.3.0'
  - '@tarojs/shared@4.3.0'
  - '@tarojs/taro-h5@4.3.0'
  - '@tarojs/taro-loader@4.3.0'
  - '@tarojs/taro@4.3.0'
  - '@tarojs/webpack5-prebundle@4.3.0'
  - '@tarojs/webpack5-runner@4.3.0'
  - babel-plugin-transform-solid-jsx@4.3.0
  - babel-plugin-transform-taroapi@4.3.0
  - babel-preset-taro@4.3.0
  - postcss-html-transform@4.3.0
  - postcss-plugin-constparse@4.3.0
  - postcss-pxtransform@4.3.0
